apiVersion: v1
kind: Service
metadata:
  name: agent-fleet
spec:
  type: NodePort
  selector:
    app: agent-fleet
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
